### ISSUE TITLE
Add support for Boolean and Guid to MappingHelper.TryProcessParameterAsString

### ISSUE THREAD

**Issue by mrbucurie** [neisbut/EntityFramework.MemoryJoin#21]
Currently, when using ValuesInjectionMethod.ViaSqlQueryBody, the data types bool and Guid are not written inline, but via command parameters.

Is it possible to add support also for these 2 data types?
Thank you in advance!

**Comment by neisbut** [comment]
Hi @mrbucurie, ok, this is easily possible for GUID and it is done in latest version. But for bool it is a bit more compliated because bool is implemented differently in different DBMS. In latest version I mapped bool to use int as an underlying storage. So true will be mapped to 1 and false to 0. I can't promise it will work for you with this change. So could you please try latest version and tell if it works?
